resources:
  - url: http://127.0.0.1:5000/linked-lovelace-card.js
    type: module
views:
  - cards:
      - type: custom:linked-lovelace-card
        name: Linked Lovelace Development
        entity: sun.sun
        test_gui: true
