name: Validate with hassfest

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v2"
        - name: HACS Action
          uses: "hacs/action@main"
          with:
            category: "plugin"
        # - uses: "home-assistant/actions/hassfest@master"